/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as vendorVendorRouteImport } from './routes/(vendor)/_vendor'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as vendorVendorPinRouteImport } from './routes/(vendor)/_vendor.pin'
import { Route as vendorVendorDashboardRouteImport } from './routes/(vendor)/_vendor.dashboard'
import { Route as vendorVendorContactUsRouteImport } from './routes/(vendor)/_vendor.contact-us'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const vendorVendorRoute = vendorVendorRouteImport.update({
  id: '/(vendor)/_vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const vendorVendorPinRoute = vendorVendorPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => vendorVendorRoute,
} as any)
const vendorVendorDashboardRoute = vendorVendorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => vendorVendorRoute,
} as any)
const vendorVendorContactUsRoute = vendorVendorContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => vendorVendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/': typeof AdminIndexRoute
  '/contact-us': typeof vendorVendorContactUsRoute
  '/dashboard': typeof vendorVendorDashboardRoute
  '/pin': typeof vendorVendorPinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin': typeof AdminIndexRoute
  '/contact-us': typeof vendorVendorContactUsRoute
  '/dashboard': typeof vendorVendorDashboardRoute
  '/pin': typeof vendorVendorPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(vendor)/_vendor': typeof vendorVendorRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/': typeof AdminIndexRoute
  '/(vendor)/_vendor/contact-us': typeof vendorVendorContactUsRoute
  '/(vendor)/_vendor/dashboard': typeof vendorVendorDashboardRoute
  '/(vendor)/_vendor/pin': typeof vendorVendorPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/admin/'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/admin'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(vendor)/_vendor'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/admin/'
    | '/(vendor)/_vendor/contact-us'
    | '/(vendor)/_vendor/dashboard'
    | '/(vendor)/_vendor/pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  vendorVendorRoute: typeof vendorVendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(vendor)/_vendor': {
      id: '/(vendor)/_vendor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vendorVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vendor)/_vendor/pin': {
      id: '/(vendor)/_vendor/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof vendorVendorPinRouteImport
      parentRoute: typeof vendorVendorRoute
    }
    '/(vendor)/_vendor/dashboard': {
      id: '/(vendor)/_vendor/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof vendorVendorDashboardRouteImport
      parentRoute: typeof vendorVendorRoute
    }
    '/(vendor)/_vendor/contact-us': {
      id: '/(vendor)/_vendor/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof vendorVendorContactUsRouteImport
      parentRoute: typeof vendorVendorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface vendorVendorRouteChildren {
  vendorVendorContactUsRoute: typeof vendorVendorContactUsRoute
  vendorVendorDashboardRoute: typeof vendorVendorDashboardRoute
  vendorVendorPinRoute: typeof vendorVendorPinRoute
}

const vendorVendorRouteChildren: vendorVendorRouteChildren = {
  vendorVendorContactUsRoute: vendorVendorContactUsRoute,
  vendorVendorDashboardRoute: vendorVendorDashboardRoute,
  vendorVendorPinRoute: vendorVendorPinRoute,
}

const vendorVendorRouteWithChildren = vendorVendorRoute._addFileChildren(
  vendorVendorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  vendorVendorRoute: vendorVendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
