/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as vendorPanelVendorRouteImport } from './routes/(vendor-panel)/_vendor'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AdminVendorsIndexRouteImport } from './routes/admin/vendors/index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin/cms/index'
import { Route as vendorPanelVendorPinRouteImport } from './routes/(vendor-panel)/_vendor.pin'
import { Route as vendorPanelVendorDashboardRouteImport } from './routes/(vendor-panel)/_vendor.dashboard'
import { Route as vendorPanelVendorContactUsRouteImport } from './routes/(vendor-panel)/_vendor.contact-us'
import { Route as AdminCmsCategoriesIndexRouteImport } from './routes/admin/cms/categories/index'
import { Route as AdminCmsBannersIndexRouteImport } from './routes/admin/cms/banners/index'
import { Route as AdminVendorsVendorIdSettingsRouteImport } from './routes/admin/vendors/$vendorId.settings'
import { Route as AdminCmsCategoriesCategoryIdRouteImport } from './routes/admin/cms/categories/$categoryId'
import { Route as AdminCmsBannersAddRouteImport } from './routes/admin/cms/banners/add'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const vendorPanelVendorRoute = vendorPanelVendorRouteImport.update({
  id: '/(vendor-panel)/_vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsIndexRoute = AdminVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => AdminRoute,
} as any)
const vendorPanelVendorPinRoute = vendorPanelVendorPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => vendorPanelVendorRoute,
} as any)
const vendorPanelVendorDashboardRoute =
  vendorPanelVendorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => vendorPanelVendorRoute,
  } as any)
const vendorPanelVendorContactUsRoute =
  vendorPanelVendorContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => vendorPanelVendorRoute,
  } as any)
const AdminCmsCategoriesIndexRoute = AdminCmsCategoriesIndexRouteImport.update({
  id: '/cms/categories/',
  path: '/cms/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsBannersIndexRoute = AdminCmsBannersIndexRouteImport.update({
  id: '/cms/banners/',
  path: '/cms/banners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsVendorIdSettingsRoute =
  AdminVendorsVendorIdSettingsRouteImport.update({
    id: '/vendors/$vendorId/settings',
    path: '/vendors/$vendorId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsCategoriesCategoryIdRoute =
  AdminCmsCategoriesCategoryIdRouteImport.update({
    id: '/cms/categories/$categoryId',
    path: '/cms/categories/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsBannersAddRoute = AdminCmsBannersAddRouteImport.update({
  id: '/cms/banners/add',
  path: '/cms/banners/add',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/contact-us': typeof vendorPanelVendorContactUsRoute
  '/dashboard': typeof vendorPanelVendorDashboardRoute
  '/pin': typeof vendorPanelVendorPinRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsRoute
  '/admin/cms/banners/': typeof AdminCmsBannersIndexRoute
  '/admin/cms/categories/': typeof AdminCmsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/contact-us': typeof vendorPanelVendorContactUsRoute
  '/dashboard': typeof vendorPanelVendorDashboardRoute
  '/pin': typeof vendorPanelVendorPinRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/vendors': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsRoute
  '/admin/cms/banners': typeof AdminCmsBannersIndexRoute
  '/admin/cms/categories': typeof AdminCmsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(vendor-panel)/_vendor': typeof vendorPanelVendorRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/(vendor-panel)/_vendor/contact-us': typeof vendorPanelVendorContactUsRoute
  '/(vendor-panel)/_vendor/dashboard': typeof vendorPanelVendorDashboardRoute
  '/(vendor-panel)/_vendor/pin': typeof vendorPanelVendorPinRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsRoute
  '/admin/cms/banners/': typeof AdminCmsBannersIndexRoute
  '/admin/cms/categories/': typeof AdminCmsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/admin/transactions'
    | '/admin/'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
    | '/admin/cms/'
    | '/admin/vendors/'
    | '/admin/cms/banners/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/vendors/$vendorId/settings'
    | '/admin/cms/banners/'
    | '/admin/cms/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/admin/transactions'
    | '/admin'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
    | '/admin/cms'
    | '/admin/vendors'
    | '/admin/cms/banners/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/vendors/$vendorId/settings'
    | '/admin/cms/banners'
    | '/admin/cms/categories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(vendor-panel)/_vendor'
    | '/admin/transactions'
    | '/admin/'
    | '/(vendor-panel)/_vendor/contact-us'
    | '/(vendor-panel)/_vendor/dashboard'
    | '/(vendor-panel)/_vendor/pin'
    | '/admin/cms/'
    | '/admin/vendors/'
    | '/admin/cms/banners/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/vendors/$vendorId/settings'
    | '/admin/cms/banners/'
    | '/admin/cms/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  vendorPanelVendorRoute: typeof vendorPanelVendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(vendor-panel)/_vendor': {
      id: '/(vendor-panel)/_vendor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vendorPanelVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/': {
      id: '/admin/vendors/'
      path: '/vendors'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AdminVendorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/cms'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(vendor-panel)/_vendor/pin': {
      id: '/(vendor-panel)/_vendor/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof vendorPanelVendorPinRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/(vendor-panel)/_vendor/dashboard': {
      id: '/(vendor-panel)/_vendor/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof vendorPanelVendorDashboardRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/(vendor-panel)/_vendor/contact-us': {
      id: '/(vendor-panel)/_vendor/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof vendorPanelVendorContactUsRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/admin/cms/categories/': {
      id: '/admin/cms/categories/'
      path: '/cms/categories'
      fullPath: '/admin/cms/categories/'
      preLoaderRoute: typeof AdminCmsCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/banners/': {
      id: '/admin/cms/banners/'
      path: '/cms/banners'
      fullPath: '/admin/cms/banners/'
      preLoaderRoute: typeof AdminCmsBannersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors/$vendorId/settings': {
      id: '/admin/vendors/$vendorId/settings'
      path: '/vendors/$vendorId/settings'
      fullPath: '/admin/vendors/$vendorId/settings'
      preLoaderRoute: typeof AdminVendorsVendorIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/categories/$categoryId': {
      id: '/admin/cms/categories/$categoryId'
      path: '/cms/categories/$categoryId'
      fullPath: '/admin/cms/categories/$categoryId'
      preLoaderRoute: typeof AdminCmsCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/banners/add': {
      id: '/admin/cms/banners/add'
      path: '/cms/banners/add'
      fullPath: '/admin/cms/banners/add'
      preLoaderRoute: typeof AdminCmsBannersAddRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
  AdminVendorsIndexRoute: typeof AdminVendorsIndexRoute
  AdminCmsBannersAddRoute: typeof AdminCmsBannersAddRoute
  AdminCmsCategoriesCategoryIdRoute: typeof AdminCmsCategoriesCategoryIdRoute
  AdminVendorsVendorIdSettingsRoute: typeof AdminVendorsVendorIdSettingsRoute
  AdminCmsBannersIndexRoute: typeof AdminCmsBannersIndexRoute
  AdminCmsCategoriesIndexRoute: typeof AdminCmsCategoriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
  AdminVendorsIndexRoute: AdminVendorsIndexRoute,
  AdminCmsBannersAddRoute: AdminCmsBannersAddRoute,
  AdminCmsCategoriesCategoryIdRoute: AdminCmsCategoriesCategoryIdRoute,
  AdminVendorsVendorIdSettingsRoute: AdminVendorsVendorIdSettingsRoute,
  AdminCmsBannersIndexRoute: AdminCmsBannersIndexRoute,
  AdminCmsCategoriesIndexRoute: AdminCmsCategoriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface vendorPanelVendorRouteChildren {
  vendorPanelVendorContactUsRoute: typeof vendorPanelVendorContactUsRoute
  vendorPanelVendorDashboardRoute: typeof vendorPanelVendorDashboardRoute
  vendorPanelVendorPinRoute: typeof vendorPanelVendorPinRoute
}

const vendorPanelVendorRouteChildren: vendorPanelVendorRouteChildren = {
  vendorPanelVendorContactUsRoute: vendorPanelVendorContactUsRoute,
  vendorPanelVendorDashboardRoute: vendorPanelVendorDashboardRoute,
  vendorPanelVendorPinRoute: vendorPanelVendorPinRoute,
}

const vendorPanelVendorRouteWithChildren =
  vendorPanelVendorRoute._addFileChildren(vendorPanelVendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  vendorPanelVendorRoute: vendorPanelVendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
